spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-ws
          uri: lb://users-ws
          predicates:
            - Path=/users/**
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka